// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Load Supabase configuration from environment variables
// Copy .env.example to .env.local and fill in your values (DO NOT commit real credentials)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Runtime guards to ensure environment variables are configured
if (!SUPABASE_URL) {
  throw new Error(
    "Missing VITE_SUPABASE_URL environment variable. " +
    "Please copy .env.example to .env.local and set VITE_SUPABASE_URL."
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_ANON_KEY environment variable. " +
    "Please copy .env.example to .env.local and set VITE_SUPABASE_ANON_KEY."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});