// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epzoplrkjbuqqyctdxqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwem9wbHJramJ1cXF5Y3RkeHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTM0NTksImV4cCI6MjA2OTQyOTQ1OX0.XL3VkpdPYpqsieCH0qvNdiDa1MM6sLAKk17-FY5MlHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});